version: '3.8'

services: 
  api-server: 
    build: .
    container_name: api-server
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npm start"
    ports:
      - ${PORT}:${PORT}
    volumes: 
      - .:/usr/app
    links: 
      - mydb
    depends_on: 
      - mydb
    environment:
      #url do DB
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
  mydb:
    image: postgres:alpine 
    container_name: api-db
    ports: 
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_NAME=${DATABASE_NAME}