version: '3.8'

services: 
  api-server: 
    build: .
    container_name: api-server
    command: sh -c "npx knex migrate:latest && npx knex seed:run && npm start"
    ports: 
      - 3333:3333
    volumes: 
      - .:/usr/app
    links: 
      - mydb
    depends_on: 
      - mydb
    environment: 
      #url do DB
      DB_HOST: api-db
      DB_USER: postgres
      DB_PASS: postgres
  mydb:
    image: postgres:alpine 
    container_name: api-db
    ports: 
      - 5432:5432
    environment: 
      - POSTGRES_PASSWORD=postgres