version: '3.8'

services: 
  app: 
    build: .
    container_name: "api-server"
    command: sh -c "npx knex migrate:latest && npm start"
    ports: 
      - 3333:3333
    volumes: 
      - .:usr/app
    links: 
      - db
    depends_on: 
      - db
    environment: 
      DB_HOST: host.docker.internal
      DB_USER: postgres
      DB_PASS: postgres
  db:
    image: postgres:alpine 
    container_name: api-db
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres