### getting spaces
http://localhost:3333/spaces

### post request for spaces
POST http://localhost:3333/spaces HTTP/1.1
content-type: application/json

{
    "name": "Lab 5",
    "description": "pipipi popopo",
    "localization": "predio informatica",
    "responsible": "Luiz",
    "special": "false",
    "justification": "lalalala",
    "disabled": "false",
    "computers": "true",
    "qtdPeople": "40",
    "extension": "123" 
}